### ISSUE TITLE
System crash while running luajit main.lua

### ISSUE THREAD

**Issue by LiberiFatali** [Moodstocks/gtsrb.torch#2]
Torch and other dependencies are installed correctly on my computer. I can run Torch examples on GPU without problems. But when I try to do "luajit main.lua", my computer crashs and restarts automatically after 'Building the network...'.

Are there any requirements about the hadrware? I have Ubuntu 14.04, CUDA 7, CuDNN on Intel Core i7, 16GB RAM, NVIDIA Titan X.

**Comment by albanD** [comment]
No there is no special requirement for hardware, as an idea, running `luajit main.lua` requires (running on a dual core machine with a GPU with 2GB of ram):
- 2.4 GB in RAM
- 1GB in GPU memory
  We also ran a lot of tests on machines very similar to yours for heavy computations.

Can you give me more informations on the exact configuration you have:
- how did you install torch (which version of torch/distro if this is what you used)?
- what version of cudnn do you use?
- is `luajit main.lua --no_cuda` working? It is really slow but you should at least see the xlua progress bar for the training (can take some time before appearing)
- do you have the possibility to make clean install of ubuntu+cuda+torch (cudnn not needed) on a new partition? Just to be sure this is not a hw problem.

**Comment by LiberiFatali** [comment]
- I used the guide on Torch website (http://torch.ch/docs/getting-started.html) to install torch7 distro.
- CuDNN v2
- 'luajit main.lua --no_cuda' has the same error. The problem lies in the process of constructing network model.
- I made a fresh installation of Nvidia driver, Cuda, Torch. I'm pretty sure that this is not a hardware problem, since I can train alexnet, googlenet, vgg... model very well.

**Comment by albanD** [comment]
I tested on all the computers I could put my hand on (including a dual core mac without GPU) and I cannot reproduce your problem.

You can look at the `networks.lua` file for what is done during the creation of the network. But it is mainly adding module to a `Sequential`. The only part of this code that is doing something else is [this](https://github.com/Moodstocks/gtsrb.torch/blob/7aefe7eb606d03819cfef8048aba12e201681362/networks.lua#L72-L82) function that computes the size of the output after the convolutions.
You can try adding some logs and pinpoint what part is causing the crash but since I cannot reproduce I cannot help you more than that.

**Comment by LiberiFatali** [comment]
And that is the problem! 
I leave function networks.convs_noutput(convs, input_size) out and set conv_output_size to a fixed value. Then the code for constructing network model becomes stable (somehow it could get pass this before a few times, but mostly crash). Thanks for your help!

**Comment by LiberiFatali** [comment]
How do we compute the number of output elements for a table of convolution layers? That **function networks.convs_noutput(convs, input_size)** crash on my PC, so I need to modify or replace it with something else.

**Comment by albanD** [comment]
Whoa this is weird. This function only perform a forward on the convolution modules...
- Computing the size is a formula if the convs kernel size, step and padding. It is way easier to use this trick where you forward a dummy input (mainly due to the optional multiscale mode that is more complex to handle analytically).
- If you replace this function with a fixed size then the training afterward works?
- Try replacing the function with [this](https://gist.github.com/albanD/26d4d14484808b144877) version. It will use a batch size of 1. This is the only difference with a forward done during training.
- If you could add some logs and pinpoint where the error comes from this may help to find the answer.

**Comment by LiberiFatali** [comment]
- Yes, everything works smoothly after setting a fixed size for that variable.
- The version with batch-size=1 also works best for all settings of cnn and locnet.

**Comment by albanD** [comment]
I updated the master branch. Everything should work properly now.
